parameters:
    pim_catalog.values_filler.product.class: Akeneo\Pim\Enrichment\Component\Product\ValuesFiller\ProductValuesFiller
    pim_catalog.values_filler.entity_with_family_variant.class: Akeneo\Pim\Enrichment\Component\Product\ValuesFiller\EntityWithFamilyVariantValuesFiller

services:
    pim_catalog.values_filler.product:
        class: '%pim_catalog.values_filler.product.class%'
        arguments:
            - '@pim_catalog.builder.product'
            - '@pim_catalog.resolver.attribute_values'
            - '@pim_catalog.repository.currency'
            - '@pim_catalog.repository.cached_attribute'
            - '@pim_catalog.factory.value'

    pim_catalog.values_filler.entity_with_family_variant:
        class: '%pim_catalog.values_filler.entity_with_family_variant.class%'
        arguments:
            - '@pim_catalog.builder.entity_with_values'
            - '@pim_catalog.resolver.attribute_values'
            - '@pim_catalog.repository.currency'
            - '@pim_catalog.family_variant.provider.entity_with_family_variant_attributes'
            - '@pim_catalog.repository.cached_attribute'
            - '@pim_catalog.factory.value'

    pim_catalog.product.fill_missing_values:
        class: 'Akeneo\Pim\Enrichment\Component\Product\ValuesFiller\FillMissingProductValues'
        arguments:
            - '@pim_catalog.repository.cached_family'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            - '@akeneo.pim.structure.query.get_attributes'

    pim_catalog.product_model.fill_missing_values:
        class: 'Akeneo\Pim\Enrichment\Component\Product\ValuesFiller\FillMissingProductModelValues'
        arguments:
            - '@pim_catalog.repository.family_variant'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
